import assert from 'node:assert/strict';
import fs from 'node:fs';
import {guides} from '../dist/guides.js';
import {lessons,position,pawnFacts,moves,moveReason} from '../dist/lessons.js';
const distinct=new Set();let placements=0,notes=0;
for(const g of guides){const l=lessons[g.id];assert(l,g.id);assert(l.summary&&l.preferences.length&&l.scope);for(const c of l.cases){let p=position(c.line);distinct.add(p.fen());placements++;for(const field of ['purpose','structure'])assert(c[field]?.length>20,g.id+' '+field);for(const field of ['ideas','pieces','targets','counters'])assert(c[field]?.length>=2,g.id+' '+field);assert(c.plans.length===2&&c.plans.every(a=>a.length===7&&a.every(Boolean)),g.id+' plans');for(let step=1;step<=moves(c.line).length;step++){const n=moveReason(c.line,step);assert(n.why&&n.threat&&n.ignore);notes++;}}}
const facts=id=>pawnFacts(position(lessons[id].cases[0].line));
assert.deepEqual(facts('vienna').white.doubled,['c']);
assert.deepEqual(facts('nimzo').white.doubled,[]);
assert.deepEqual(facts('french-winawer').white.doubled,['c']);
assert.deepEqual(facts('rossolimo').black.doubled,['c']);
assert(!facts('caro-exchange').white.isolated.includes('d4'));
assert(facts('caro-exchange').semiWhite.includes('e'));
assert(!facts('tarrasch').black.isolated.includes('d5'));
const iqp=lessons.tarrasch.cases.find(c=>c.label.includes('완료'));
assert(pawnFacts(position(iqp.line)).black.isolated.includes('d5'));
const berlin=position(lessons.berlin.cases[0].line);
assert(!berlin.board().flat().some(x=>x?.type==='q'));assert.equal(berlin.get('d8').type,'k');
assert.equal(position(lessons['kings-indian'].cases[0].line).get('d4').type,'p');
const kidex=lessons['kings-indian'].cases.find(c=>c.label.startsWith('교환형'));
assert(pawnFacts(position(kidex.line)).open.includes('d'));
assert(!kidex.plans.flat().some(x=>x.includes('e열')));
assert.deepEqual(facts('moscow').black.doubled,[]);
assert(!facts('closed-sicilian').semiBlack.includes('c'));
assert(facts('smith-morra').open.includes('c'));
const accepted=lessons.vienna.cases.find(c=>c.label.includes('수락'));
assert.equal(position(accepted.line).get('f4').color,'b');
assert(moveReason('e4 e5 Nc3 Nf6 f4 d5',6).why.includes('중앙'));
assert(!moveReason('e4 e5 Nc3 Nf6 Bc4 Nc6 d3',7).why.includes('f6 나이트를 공격'));
const report={guides:guides.length,lessonPlacements:placements,distinctPositions:distinct.size,annotatedMoveChecks:notes,structuralRegressionChecks:18,failures:[]};
fs.mkdirSync('outputs',{recursive:true});fs.writeFileSync('outputs/strategy-validation.json',JSON.stringify(report,null,2));console.log(report);
